services:
  levantamentop-services:
    container_name: "levantamento-api"
    build: "./"
    ports:
      - "3000:3000"
  mysql:
    container_name: "data-base-container"
    build: "./Database/mysql"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
